### ISSUE TITLE
Error when flashing on cm13 at LG H815 (nightly 2016-05-29)

### ISSUE THREAD

**Issue by ghost** [nagalun/needle-zip#1]
Getting error:

Disassembling framework.jar ...
<dalvikvm> CANNOT LINK EXECUTABLE: "/system/lib/liblog.so" is 32-bit instead of 64-bit
<dalvikvm> page record for 0x7fad910010 was not found (block_size=32)
Prozess Updater endete mit FEHLER: 1
Fehler beim Installieren von ZIP.

**Comment by nagalun** [comment]
Interesting, I never tested this on 64 bit phones, I don't know much about these, but do you have a /system/lib64/liblog.so?

**Comment by ghost** [comment]
yes the file is there.

**Comment by nagalun** [comment]
Sorry for taking that much time, try out the test.zip

**Comment by ghost** [comment]
Thanks but im sorry to tell you it did not work.
Disassembling....
Something weird happened ... Error 1 appears in twrp 3.0.0

**Comment by ghost** [comment]
Do you need More info? Before flashing test Version i uninstalled xposed 80 arm64.

**Comment by nagalun** [comment]
Yeah, can you download needle.tar and do these commands from inside android as root? (In ADB or a terminal emulator, doesn't matter)

```
mount -o rw,remount /
mkdir /tmp
cp /sdcard/needle.tar /tmp/
cd /tmp/
tar xf needle.tar
mkdir /tmp/unzip
mkdir /tmp/out
unzip -o /system/framework/framework.jar -d /tmp/unzip/
dalvikvm -cp jars/baksmali-dvk.jar org.jf.baksmali.main -o out/ unzip/classes.dex
```

Tell me if dalvikvm gives an error (modify the cp /sdcard/needle.tar to point to where it is on your phone)

**Comment by ghost** [comment]
There was no error.

u0_a122@h815:/ $ su
root@h815:/ # mount -o rw,remount /
root@h815:/ # mkdir /tmp
root@h815:/ # cp /storage/emulated/0/needle.zar /tmp/
cp: bad '/storage/emulated/0/needle.zar': No such file or directory
1|root@h815:/ # cp /storage/emulated/0/needle.tar /tmp/
root@h815:/ # cd /tmp
root@h815:/tmp # tar xf needle.tar
root@h815:/tmp # ls
bin fillinsig.smali jars needle.tar patch.py
root@h815:/tmp # mkdir /tmp/unzip
root@h815:/tmp # mkdir out
p -o /system/framework/framework.jar -d /tmp/unzip/               <
Archive:  /system/framework/framework.jar
   creating: /tmp/unzip/META-INF/
  inflating: /tmp/unzip/META-INF/MANIFEST.MF
  inflating: /tmp/unzip/classes2.dex
  inflating: /tmp/unzip/classes.dex
i-dvk.jar org.jf.baksmali.main -o out/ unzip/classes.dex          <
root@h815:/tmp # ls
bin fillinsig.smali jars needle.tar out patch.py unzip
root@h815:/tmp #

**Comment by nagalun** [comment]
Try these after all of the above:

```
mkdir /tmp/out/smali
mv /tmp/out/android /tmp/out/smali/
LD_LIBRARY_PATH="/tmp/bin/lib" "/tmp/bin/python3" patch.py
```

If those actually work post the output of:

```
echo $BOOTCLASSPATH
```

**Comment by ghost** [comment]
Im currently backing up my newly configured and documented mobile system. I'll test then.

**Comment by ghost** [comment]
u0_a122@h815:/ $ su
root@h815:/ # cd sto*
root@h815:/storage # cd em*
root@h815:/storage/emulated # cd 0
root@h815:/storage/emulated/0 # sh test.sh
Archive:  /system/framework/framework.jar
   creating: /tmp/unzip/META-INF/
  inflating: /tmp/unzip/META-INF/MANIFEST.MF
  inflating: /tmp/unzip/classes2.dex
  inflating: /tmp/unzip/classes.dex
**\* Done. Now this won't hurt a bit...
**\* Injection successful.
/system/framework/core-libart.jar:/system/framework/conscrypt.jar:/system/framework/okhttp.jar:/system/framework/core-junit.jar:/system/framework/bouncycastle.jar:/system/framework/ext.jar:/system/framework/framework.jar:/system/framework/telephony-common.jar:/system/framework/voip-common.jar:/system/framework/ims-common.jar:/system/framework/apache-xml.jar:/system/framework/org.apache.http.legacy.boot.jar
root@h815:/storage/emulated/0 #

Hmm... It seems to work within terminal Emulator. But why does the ZIP flash fail?

**Comment by nagalun** [comment]
It must be some variables not set correctly. I don't have a 64 bit device to test this on, so can you run the test.sh under the recovery?, but first do this:

```
mount /system
export BOOTCLASSPATH=/system/framework/core-libart.jar:/system/framework/conscrypt.jar:/system/framework/okhttp.jar:/system/framework/core-junit.jar:/system/framework/bouncycastle.jar:/system/framework/ext.jar:/system/framework/framework.jar:/system/framework/telephony-common.jar:/system/framework/voip-common.jar:/system/framework/ims-common.jar:/system/framework/apache-xml.jar:/system/framework/org.apache.http.legacy.boot.jar
export PATH=/system/bin:/system/xbin
export LD_LIBRARY_PATH=/system/lib64:/system/lib
```

**Comment by ghost** [comment]
Does the patch.py line of test.sh alter my system or is this only in a separate folder for testing?
How can I run those commands in front of test.sh within TWRP? Is there a terminal?

**Comment by nagalun** [comment]
If you are using 3.0.0+ there is one in the Advanced menu, there is one in older versions, but it's painful to use.
(You can use 'adb shell' too)

**Comment by ghost** [comment]
I am using tingle by the meantime.

**Comment by ale5000-git** [comment]
I will add also an option to create a flashable zip to Tingle in the future, I just don't have the time yet.
