### ISSUE TITLE
backsmali-dvk and smali-dvk

### ISSUE THREAD

**Issue by ale5000-git** [nagalun/needle-zip#3]
@nagalun
Hi,
where did you get backsmali-dvk.jar and smali-dvk.jar?

**Comment by nagalun** [comment]
Those files are from mar-v-in, they were used in the freecyngn repo (to decompile some apps with bad google code and remove it).
You can download them here (v0.5 release is the last one to include the jars):
https://github.com/mar-v-in/freecyngn/releases

**Comment by ale5000-git** [comment]
Thanks :)

**Comment by ale5000-git** [comment]
@nagalun: I have been able to convert latest version of smali/backsmali to dalvik and make my fork of Needle working inside Android, if you want you can take them [here](https://github.com/ale5000-git/tingle).

PS: From my tests baksmali need just 64MB, instead smali with a single thread need about 166MB of heap.
